  # Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.Server.csproj'
    arguments: '--configuration Release --output $(build.artifactstagingdirectory) --self-contained -r win-x86'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-as-you-go(30bc7907-5dde-43b8-8545-093ea6c2942e)'
    appType: 'webApp'
    WebAppName: 'BimKrav'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/Server'
